const DB_NAME = `"C##STOCKDB"`;

module.exports = {
    USER : `${DB_NAME}."USER"`,
    USER_USER_ID : `${USER}."USER_ID"`,
    

    STOCK : `${DB_NAME}."STOCK"`,
    STOCK_SYMBOL : `${STOCK}."SYMBOL"`,
    STOCK_CORP_ID : `${STOCK}."CORP_ID"`,
    STOCK_UPDATE_TIME : `${STOCK}."UPDATE_TIME"`,
    STOCK_VALUE : `${STOCK}."VALUE"`,
    STOCK_PRICE : `${STOCK}."PRICE"`,
    STOCK_LTP : `${STOCK}."LTP"`,
    STOCK_AVAILABLE_LOTS : `${STOCK}."AVAILABLE_LOTS"`,
    STOCK_LOT : `${STOCK}."LOT"`,
    STOCK_BLOCKED : `${STOCK}."BLOCKED"`,

    ORDER : `${DB_NAME}."ORDER"`,
    ORDER_ORDER_ID : `${ORDER}."ORDER_ID"`,
    ORDER_SYMBOL : `${ORDER}."SYMBOL"`,
    ORDER_USER_ID : `${ORDER}."USER_ID"`,
    ORDER_SECTOR : `${ORDER}."SECTOR"`,
    ORDER_STATUS : `${ORDER}."STATUS"`,
    ORDER_TYPE : `${ORDER}."TYPE"`,
    ORDER_LATEST_TRADE_PRICE : `${ORDER}."LATEST_TRADE_PRICE"`,
    ORDER_LATEST_QUANTITY : `${ORDER}."LATEST_QUANTITY"`,
    ORDER_LATEST_UPDATE_TIME : `${ORDER}."LATEST_UPDATE_TIME"`,
    ORDER_TRANSACTION_FEE : `${ORDER}."TRANSACTION_FEE"`,
    ORDER_TRANSACTION_TIME : `${ORDER}."TRANSACTION_TIME"`,
    
    

}